---
- name: Set time zone
  hosts: default
  gather_facts: false
  sudo: true
  vars:
    timezone: Europe/Amsterdam

  tasks:
    - name: Set time zone variables
      copy: content='{{ timezone }}'
            dest=/etc/timezone
            owner=root
            group=root
            mode=0644
            backup=yes
      notify:
        - Update time zone

  handlers:
    - name: Update time zone
      command: dpkg-reconfigure --frontend noninteractive tzdata

- name: Install VDE
  hosts: default
  gather_facts: false
  sudo: true

  tasks:
    - name: Update APT cache
      apt: update_cache=yes

    - name: Install PHP
      apt: pkg=php5

    - name: Install PHP Curl extension
      apt: pkg=php5-curl

    - name: Install PHP XDebug extension
      apt: pkg=php5-xdebug

    - name: Install PHP MongoDB extension
      apt: pkg=php5-mongo

    - name: Install Composer
      shell: curl -sS https://getcomposer.org/installer | php

    - name: Add Composer to bin
      file: dest=/usr/local/bin/composer
            src=/home/vagrant/composer.phar
            state=link

    - name: Install Docker
      apt: pkg=docker.io

    - name: Install GIT
      apt: pkg=git

- name: Prepare VDE projects
  hosts: default
  gather_facts: false
  sudo: false

  tasks:
    - name: Copy GIT configuration
      copy: src=~/.gitconfig
            dest=/home/vagrant/.gitconfig
            force=yes

    - name: Create workspace
      file: dest=/vagrant/projects
            state=directory

    - name: Determine project status
      stat: path=/vagrant/projects/librarian
      register: librarian

    - name: Clone GIT repository Librarian
      git: repo=git@github.com:martyn82/librarian.git
           dest=/vagrant/projects/librarian
           accept_hostkey=true
      when: librarian.stat.isdir is not defined or not librarian.stat.isdir

    - name: Composer install Librarian
      command: composer install
               chdir=/vagrant/projects/librarian

- name: Finalize VDE
  hosts: default
  gather_facts: false
  sudo: false

  tasks:
    - name: Link projects to home
      file: path=/home/vagrant/p
            src=/vagrant
            state=link
