---
- name: Set time zone
  hosts: default
  gather_facts: false
  sudo: true
  vars:
    timezone: Europe/Amsterdam

  tasks:
    - name: Set time zone variables
      copy: content='{{ timezone }}'
            dest=/etc/timezone
            owner=root
            group=root
            mode=0644
            backup=yes
      notify:
        - Update time zone

  handlers:
    - name: Update time zone
      command: dpkg-reconfigure --frontend noninteractive tzdata

- name: Install VDE
  hosts: default
  gather_facts: false
  sudo: true

  tasks:
    - name: Update APT cache
      apt: update_cache=yes

    - name: Install Java runtime
      apt: pkg=default-jre

    - name: Install Unzip
      apt: pkg=unzip

    - name: Install GIT
      apt: pkg=git

    - name: Install NPM
      apt: pkg=npm

    - name: Install NodeJS legacy package
      apt: pkg=nodejs-legacy

    - name: Install PHP
      apt: pkg=php5

    - name: Install PHP Curl extension
      apt: pkg=php5-curl

    - name: Install PHP XDebug extension
      apt: pkg=php5-xdebug

    - name: Install PHP MongoDB extension
      apt: pkg=php5-mongo

    - name: Install MongoDB client
      apt: pkg=mongodb-clients

    - name: Check Composer installation
      stat: path=/usr/local/bin/composer
      register: composer

    - name: Install Composer
      shell: curl -sS https://getcomposer.org/installer | php
      when: not composer.stat.exists

    - name: Add Composer to bin
      file: dest=/usr/local/bin/composer
            src=/home/vagrant/composer.phar
            state=link
      when: not composer.stat.exists

    - name: Check Docker installation
      stat: path=/usr/bin/docker
      register: docker

    - name: Install Docker
      shell: wget -qO- https://get.docker.com/ | sh
      when: not docker.stat.exists

    - name: Add Docker user group
      shell: groupadd docker || true

    - name: Add user to Docker group
      shell: gpasswd -a vagrant docker

    - name: Restart Docker service
      shell: service docker restart

    - name: Check Sonar runner installation
      stat: path=/usr/local/bin/sonar-runner
      register: sonar

    - name: Download Sonar runner
      shell: wget http://repo1.maven.org/maven2/org/codehaus/sonar/runner/sonar-runner-dist/2.4/sonar-runner-dist-2.4.zip && unzip sonar-runner-dist-2.4.zip
      when: not sonar.stat.exists
      notify:
        - Clean Sonar runner download

    - name: Install Sonar runner
      command: mv sonar-runner-2.4 /opt/sonar-runner
               creates=/opt/sonar-runner
               removes=sonar-runner-2.4
      when: not sonar.stat.exists

    - name: Add Sonar runner to bin
      file: dest=/usr/local/bin/sonar-runner
            src=/opt/sonar-runner/bin/sonar-runner
            state=link
      when: not sonar.stat.exists

    - name: Install display server
      apt: pkg=xvfb

    - name: Download Google Chrome stable
      shell: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

    - name: Install Google Chrome stable
      shell: dpkg --force-depends -i google-chrome-stable_current_amd64.deb ; apt-get -fy install

  handlers:
    - name: Clean Sonar runner download
      file: path=sonar-runner-dist-2.4.zip
              state=absent

- name: Prepare VDE projects
  hosts: default
  gather_facts: false
  sudo: false

  tasks:
    - name: Start display server
      shell: if pgrep Xvfb > /dev/null ; then true; else start-stop-daemon --start -b -x /usr/bin/Xvfb -- :0 -screen 0 1024x768x24 -ac ; fi

    - name: Copy GIT configuration
      copy: src=~/.gitconfig
            dest=/home/vagrant/.gitconfig
            force=yes

    - name: 'Librarian: Determine project status'
      stat: path=/home/vagrant/p/librarian
      register: librarian

    - name: 'Librarian: Clone GIT repository'
      local_action: git repo=git@github.com:martyn82/librarian.git
                    dest=../projects/librarian
                    accept_hostkey=true
      when: librarian.stat.isdir is not defined or not librarian.stat.isdir

    - name: 'Librarian: Composer install'
      command: composer install
               chdir=/home/vagrant/p/librarian
